### ISSUE TITLE
C# Hello world

### ISSUE THREAD

**Issue by arialdomartini** [adunicorn/prototypes#1]
@emanuelefirmani, il primo obiettivo fisso è di avere su questo repository:

* una console application in C# che stampi `Hello world` (su Mono o DotNetCore)
* uno script capace di creare l'immagine docker con la console application
* uno script per lanciare un container su quell'immagine

Tutto deve essere in grado:

*  di essere eseguibile senza bisogno di alcuna installazione se non `Docker`
*  di essere eseguibile senza errori sia sul mio Linux che sul tuo Windows

Per cui, mi aspetto due coppie di comandi (una per Linux, una per Windows):

* `build.bat` e `build.sh` per creare l'immagine;
* `run.bat` e `run.sh` per lanciare il container.

**Comment by emanuelefirmani** [comment]
Hope this issue is fixed
